"""Add first_name, last_name, phone_number to user table

Revision ID: 2dbccd097361
Revises: def789ghi012
Create Date: 2025-12-15 07:28:08.141589+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbccd097361'
down_revision: Union[str, Sequence[str], None] = 'def789ghi012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_constraint(op.f('session_user_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    
    # Add new columns to user table
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('user', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    
    # FIXED: Keep email unique constraint and add phone_number unique constraint
    # op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')  # REMOVED THIS LINE
    op.create_unique_constraint('uq_user_phone_number', 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop phone_number unique constraint
    op.drop_constraint('uq_user_phone_number', 'user', type_='unique')
    
    # FIXED: Don't recreate email constraint as it was never dropped
    # op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    
    op.alter_column('user', 'is_verified',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('true'),
                    existing_nullable=False)
    
    # Drop new columns
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_id_fkey'), 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.alter_column('session', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('true'),
                    existing_nullable=False)
    # ### end Alembic commands ###